/* Auto-generated by tools/gen_dynacache_hashes.py. Do not edit. */
#ifndef __DYNACACHE_HASHES_H__
#define __DYNACACHE_HASHES_H__

#define DYNAREC_VERSION 0x4D854Du

#if defined(ARM64)
#define ARCH_VERSION 0x1126D0u
#elif defined(RV64)
#define ARCH_VERSION 0x381CDBu
#elif defined(LA64)
#define ARCH_VERSION 0x665E69u
#elif defined(PPC64LE)
#define ARCH_VERSION 0xE4F831u
#else
#error Unsupported architecture
#endif

#endif
